# Generated by Django 5.0.6 on 2024-05-31 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='вкусный рецепт', max_length=40),
        ),
    ]
